project: 'FM-IRL'
program: fmirl/main.py
method: grid
name: Walker-FM-BC-1traj
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  - --use-proper-time-limits
parameters:
  prefix:
    value: fm-bc
  alg:
    value: fm-bc
  env-name:
    value: Walker2d-v3
  normalize-env:
    value: False
  traj-load-path:
    value: ./expert_datasets/ppo_walker_1.pt
  bc-num-epochs:
    value: 1000
  eval-num-processes:
    value: 20
  traj-frac:
    value: 0.5
  traj-val-ratio:
    value: 0.2
  seed:
    values: [1,2,3,4]


