# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

project: 'FM-IRL'
program: fmirl/main.py
method: grid
name: hopper-ppo
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  
parameters:
  alg:
    value: ppo
  clip-actions:
    value: true
  cuda:
    value: true
  entropy-coef:
    value: 0.001
  env-name:
    value: hopper-medium-v0
    
  eval-interval:
    value: 20000
  eval-num-processes:
    value: 1
  log-interval:
    value: 1
  lr:
    value: 0.0001
  max-grad-norm:
    value: 0.5
  normalize-env:
    value: true
  num-env-steps:
    value: 25000000
  num-epochs:
    value: 10
  num-eval:
    value: 2
  num-mini-batch:
    value: 32
  num-render:
    value: 1000
  num-steps:
    value: 256
  ppo-hidden-dim:
    value: 256
  prefix:
    value: ppo
  save-interval:
    value: 100000
  seed:
    value: 1
  vid-fps:
    value: 100
    