# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

project: 'FM-IRL'
program: fmirl/main.py
method: grid
name: Ant-wail-0.00
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  - --use-proper-time-limits
  - --render-metric 

parameters:
  prefix:
    value: wail
  alg:
    value: wail
  env-name:
    value: AntGoal-v0
  traj-load-path:
    value: ./expert_datasets/ant_50.pt
  cuda:
    value: True
  num-steps:
    value: 500
  traj-frac:
    value: 0.5
  ant-noise:
    value: 0.0
  action-input:
    value: True
  num-epochs:
    value: 10
  num-mini-batch:
    value: 32
  wail-reward-norm:
    value: True
  entropy-coef:
    value: 0.001
  lr:
    value: 0.0001
  disc-lr:
    value: 0.0001
  ppo-hidden-dim:
    value: 256
  seed: 
    values: [1,2,3,4,5]
  regularize-epsilon:
    value: 0.01
  num-env-steps:
    value: 5000000