# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

project: 'FM-IRL'
program: fmirl/main.py
method: grid
name: hopper-fm-bc-1traj

parameters:
  seed:
    values: [1,2,3,4]
    # value: 1
  prefix:
    value: "fm-bc"
  alg:
    value: "fm-bc"
  traj-load-path:
    value: ./expert_datasets/ppo_hopper_1.pt
  env-name:
    value: "hopper-medium-v0"
  normalize-env:
    value: False
  bc-num-epochs:
    value: 5000
  eval-num-processes:
    value: 10
  cuda:
    value: True
  num-render:
    value: 0
  num-eval:
    value: 10
  vid-fps:
    value: 100
  lr:
    value: 0.0001
  log-interval:
    value: 1000
  save-interval:
    value: 100000
  eval-interval:
    value: 1000
  bc-state-norm:
    value: True
  clip-actions:
    value: True
