

project: 'FM-IRL'
program: fmirl/main.py
method: grid
name: Example-with-local-logging

parameters:

  log-dir:
    value: "./data/local_logs"         
  enable-local-logging:
    value: True                       
  log-smooth-len:
    value: 10                          
  log-interval:
    value: 1                           
 
  seed:
    values: [1, 2, 3, 4]
  prefix:
    value: "fmail-local-log"
  alg:
    value: "fmail"
  env-name:
    value: "Walker2d-v3"
 
  num-env-steps:
    value: 8000000
  eval-interval:
    value: 200
  save-interval:
    value: 100000
    

  lr:
    value: 0.0001
  disc-lr:
    value: 0.001